# This is a basic workflow to help you get started with Actions

name: output-workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  issues:
    types: [opened, edited, reopened, closed]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  issue-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Show issue information
        run: |
          echo "Issue ${GITHUB_EVENT_NAME} ${GITHUB_EVENT_ACTION}:"
          echo "Title: ${GITHUB_EVENT_ISSUE_TITLE}"
          echo "Number: ${GITHUB_EVENT_ISSUE_NUMBER}"
          echo "State: ${GITHUB_EVENT_ISSUE_STATE}"
          echo "Body: ${GITHUB_EVENT_ISSUE_BODY}"
