# This is a basic workflow to help you get started with Actions

name: workflow-1

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint :
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - name: Run a one-line script
            run: npm install | npm install vitest 
          - name: Linting
            run: npm run lint
  test :
        needs: lint
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - name: Testing
            run: npm run test
  build :
        needs: test
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - name: Building
            run: npm run build
          - name: Message
            run: echo "Lined , tested and built"
